### PR TITLE
Added support of Sequel 5.*

### PR DESCRIPTION
**Pull request by mr-dxdy**

### CODE REVIEW

**Comment by mr-dxdy** [comment]
@mpalmer,  please look at my pull request

**Comment by TSMMark** [comment]
@mpalmer can we merge this? Want to use this package but it is not fully compatible

**Comment by TSMMark** [comment]
Even this fork seems to be unsupported now

```
[2021-02-25T21:08:16Z] Fetching https://github.com/mr-dxdy/sequel-pg-comment.git
  | [2021-02-25T21:08:17Z]
  | [2021-02-25T21:08:17Z] [!] There was an error while loading `sequel-pg-comment.gemspec`: cannot load such file -- git-version-bump
  | [2021-02-25T21:08:17Z] Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.
  | [2021-02-25T21:08:17Z]
  | [2021-02-25T21:08:17Z]  #  from /usr/local/bundle/ruby/3.0.0/bundler/gems/sequel-pg-comment-08eb74311955/sequel-pg-comment.gemspec:1
  | [2021-02-25T21:08:17Z]  #  -------------------------------------------
  | [2021-02-25T21:08:17Z]  >  require 'git-version-bump'
  | [2021-02-25T21:08:17Z]  #
  | [2021-02-25T21:08:17Z]  #  -------------------------------------------
```

**Comment by TSMMark** [comment]
Forked and updated for compatibility https://github.com/TSMMark/sequel-pg-comment/tree/remove-git-version-bump

Also added support for reversible Sequel migration `change`, so you don't have to manually write `up` and `down` blocks in your migration in order for your migration to be reversible when using `comment_on`: https://github.com/mpalmer/sequel-pg-comment/commit/42ff4c048635aa619b525f72379d9ff6d0936fdc

**Pull request merged**
